### ISSUE TITLE
React and next dependency conflict

### ISSUE THREAD

**Issue by Razamindset** [rajput-hemant/infinitunes#61]
![image](https://github.com/user-attachments/assets/e56fdf7e-8230-4ef2-b12a-b6c6a7538add)
I pulled the latest changes now and on installing the packages I encountered a dependency conflict. Take a look.

**Comment by rajput-hemant** [comment]
@Razamindset https://github.com/rajput-hemant/infinitunes/issues/42#issuecomment-2226745502

**Comment by Razamindset** [comment]
I have tried the fix using npm and also tried bun. On npm it showed me a million warnings and no complete installation and on bun it is also stuck on the installation phase. I think you should not rush to the canary the Rc version was working perfeclty?? :) ...
![image](https://github.com/user-attachments/assets/109d7e45-153b-4fac-91b9-67846da17652)

**Comment by Razamindset** [comment]
npm was not working it showed bunch of errors I used bun and it solved the installation issue :) Thanks
