### ISSUE TITLE
Eslint config issue

### ISSUE THREAD

**Issue by Razamindset** [rajput-hemant/infinitunes#62]
Eslint wants me to have a config file
![image](https://github.com/user-attachments/assets/1be170ba-87ee-4300-8eaa-78c337719e47)
help is appreciated :)

**Comment by Razamindset** [comment]
Anyone ?

**Comment by rajput-hemant** [comment]
Hey @Razamindset,

I apologize for the delayed resolution. I didn’t notice this issue until just now.

**Comment by Razamindset** [comment]
Np :)
